// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqsqb6eFOu1moLtbD2acVFQlbMJF0lt0',
    appId: '1:352503046025:web:80a1ef9be59f02b68d8b58',
    messagingSenderId: '352503046025',
    projectId: 'my-chat-a1d58',
    authDomain: 'my-chat-a1d58.firebaseapp.com',
    storageBucket: 'my-chat-a1d58.appspot.com',
    measurementId: 'G-DVS4SWHB99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6HLQ4VzWx7u3PtlDIsTF_btkPqnkHaSM',
    appId: '1:352503046025:android:0d850597efbfe4858d8b58',
    messagingSenderId: '352503046025',
    projectId: 'my-chat-a1d58',
    storageBucket: 'my-chat-a1d58.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqsqb6eFOu1moLtbD2acVFQlbMJF0lt0',
    appId: '1:352503046025:web:f565f896001c16ca8d8b58',
    messagingSenderId: '352503046025',
    projectId: 'my-chat-a1d58',
    authDomain: 'my-chat-a1d58.firebaseapp.com',
    storageBucket: 'my-chat-a1d58.appspot.com',
    measurementId: 'G-6JBPLKVFFP',
  );
}
